### ISSUE TITLE
Anchors are hidden behind header

### ISSUE THREAD

**Issue by berlindave** [wp-berlin/tech-website#26]
When I try i. e. to link to the second topic of the Meetup 001, @hofmannsven's topc "Content Security Policy (CSP)", I can do this by using the ID of the title: https://tech.wpmeetup-berlin.de/meeting-minutes/001/#content-security-policy-csp

It works, but the section seems to start at the top of the browser window behind the header, so the title and first paragraph is hidden by the header. Is there a (reasonably simple) solution to this issue?

**Comment by berlindave** [comment]
This issue probably is linked to #12.

**Comment by hofmannsven** [comment]
Yes, I also noticed this when linking the topics in the notes.
There is a [demo](https://css-tricks.com/examples/HashLinksWithPadding/pseudo.php) with a workaround on [CSS-Tricks](https://css-tricks.com/hash-tag-links-padding/#article-header-id-1).
I think I can have a look at this in the next couple of days.

```css
h2:before { 
  display: block; 
  content: " "; 
  margin-top: -236px; 
  height: 236px;
  visibility: hidden; 
  pointer-events: none;
}
```
